GHL/Controllers/GymController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace GHL.Controllers
{
    public class GymController : Controller
    {
        // GET: Gym
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult Amenities()
        {
            return View();
        }

        public ActionResult Gallery()
        {
            return View();
        }

        public ActionResult Contact()
        {
            return View();
        }
    }
}

GHL/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace GHL.Controllers
{
    public class HomeController : Controller
    {
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult About()
        {
            ViewBag.Message = "Your application description page.";

            return View();
        }

        public ActionResult Contact()
        {
            ViewBag.Message = "Your contact page.";

            return View();
        }

        public ActionResult Login()
        {
            return View();
        }

        public ActionResult Register()
        {
            return View();
        }
    }
}

GHL/Controllers/HostelController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace GHL.Controllers
{
    public class HostelController : Controller
    {
        // GET: Hostel
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult Amenities()
        {
            return View();
        }

        public ActionResult Gallery()
        {
            return View();
        }

        public ActionResult Contact()
        {
            return View();
        }
    }
}

GHL/Controllers/LibraryController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace GHL.Controllers
{
    public class LibraryController : Controller
    {
        // GET: Library
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult Amenities()
        {
            return View();
        }

        public ActionResult Gallery()
        {
            return View();
        }

        public ActionResult Contact()
        {
            return View();
        }
    }
}

GHL/Views/Gym/Amenities.cshtml
@{
    ViewBag.Title = "Amenities";
    Layout = "~/Views/Shared/_LayoutGym.cshtml";
}

<style>
    .gym-home {
        background: linear-gradient(rgba(25, 24, 24, 0.4), rgba(23, 22, 23, 0.5)), url(../../images/gym-header.jpg) no-repeat;
        background-size: cover;
        min-height: 250px;
        background-attachment: fixed;
    }
</style>

<div class="gym-home p-5">
    <div class="row p-5">
        <div class="col-12"></div>
    </div>
    <div class="row">
        <div class="col-12 pl-5">
            <h2 class="media-heading pb-0 text-white pt-5 ml-5">Amenities</h2>
        </div>
    </div>
</div>
<div class="team">
    <div class="container">
        <div class="row mt-3">
            <div class="col-6">
                <div class="card border-0">
                    <div class="card-body">
                        <img src="~/images/group-workout.jpg" />
                    </div>
                </div>
            </div>
            <div class="col-6 p-3">
                <div class="card border-0">
                    <h3 class="card-title ml-3 mt-3">Group Exercise</h3>
                    <div class="card-body">
                        <p>Our temperature-controlled group exercise studios boast special flooring, sound systems and over 50 Les Mills, Zumba and Mind & Body classes per week.</p>
                    </div>
                </div>
            </div>
        </div>

        <div class="row mt-3">
            <div class="col-6">
                <div class="card border-0">
                    <h3 class="card-title ml-3 mt-3">Personal Training</h3>
                    <div class="card-body">
                        <p>Our Certified Personal Trainers deliver the highest-quality instruction and motivation to help you meet and surpass your fitness goals.</p>
                    </div>
                </div>
            </div>
            <div class="col-6">
                <div class="card border-0">
                    <div class="card-body">
                        <img src="~/images/personal-trainer.jpg" />
                    </div>
                </div>
            </div>
        </div>

        <div class="row mt-3">
            <div class="col-6">
                <div class="card border-0">
                    <div class="card-body">
                        <img src="~/images/cardio-equipment.jpg" />
                    </div>
                </div>
            </div>
            <div class="col-6 p-3">
                <div class="card border-0">
                    <h3 class="card-title ml-3 mt-3">Cardio Equipment</h3>
                    <div class="card-body">
                        <p>We've built our reputation on a no-compromises approach to fitness. That is why you’ll find many cutting-edge cardio equipment from the top manufacturers – all maintained to the highest standard of performance.</p>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

GHL/Views/Gym/Contact.cshtml
@{
    ViewBag.Title = "Contact";
    Layout = "~/Views/Shared/_LayoutGym.cshtml";
}
<div class="innerpage-banner">
    <div class="layer1">
    </div>
</div>
<!-- //inner page banner -->
<!-- contact -->
<section class="w3ls-section contact py-5">
    <div class="container py-sm-3">
        <div class="w3ls-title">
            <h2 class="heading text-center mb-sm-5 mb-4">Get in touch</h2>
        </div>
        <div class="w3ls_map">
            <iframe src="https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d3501.967389821937!2d77.27669126440718!3d28.630739440914414!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x390cfcab758ca079%3A0x412350daeeab102!2sAIIPS%20LIBRARY%20(1)!5e0!3m2!1sen!2sin!4v1604383315835!5m2!1sen!2sin"></iframe>
        </div>

        <div class="row contact_wthreerow agileits-w3layouts">

            <div class="col-lg-5 col-md-6 agileits_w3layouts_contact_gridl">
                <div class="agileits_mail_grid_right_grid">
                    <h4>Contact Address</h4>
                    <p>Feel free to reach us for any queries, enquiry or complaint. We are listening to your suggestions to make our services better than ever.</p>
                    <ul class="contact_info">
                        <li><span class="fa fa-map-marker" aria-hidden="true"></span>A1/470 Main Market, Shakarpur, East Delhi-110092<span class="left"> </span>.</li>
                        <li><span class="fa fa-envelope" aria-hidden="true"></span><a href="mailto:info@example.com">info@adventuretravelpoint.com</a></li>
                        <li><span class="fa fa-phone" aria-hidden="true"></span>+(91)-9871775527, 9953495340, 9953495341, 9953495343, 9953495344</li>
                        <li><span class="fa fa-globe" aria-hidden="true"></span><a href="#">adventuretravelpoint.com</a></li>
                    </ul>
                </div>
            </div>
            <div class="col-lg-7 col-md-6 mt-md-0 mt-5 w3l_contact_form">
                <h4>Contact Form</h4>
                <form action="#" method="post">
                    <input type="text" name="Name" value="Name" onfocus="this.value = '';" onblur="if (this.value == '') {this.value = 'Name';}"
                           required="">
                    <input type="email" name="Email" value="Email" onfocus="this.value = '';" onblur="if (this.value == '') {this.value = 'Email';}"
                           required="">
                    <input type="text" name="Phone" value="Phone" onfocus="this.value = '';" onblur="if (this.value == '') {this.value = 'Phone';}"
                           required="">
                    <textarea name="Message" onfocus="this.value = '';" onblur="if (this.value == '') {this.value = 'Message...';}" required="">Message...</textarea>
                    <input type="submit" value="Submit">
                </form>
            </div>
        </div>
    </div>
</section>
<!-- //contact -->

GHL/Views/Home/Index.cshtml
@{
    ViewBag.Title = "Home Page";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<!-- banner-text -->
<div class="slider">
    <div class="callbacks_container">
        <ul class="rslides callbacks callbacks1" id="slider4">
            <li>
                <div class="banner-top">
                    <div class="layer">
                        <div class="container">
                            <div class="banner-info_agile_w3ls">
                                <h2>Your <span>Fitness</span> Destination. </h2>
                                <p>Weight loss, weight training, bodybuilding and more...</p>
                                @*<a href="About" class="mr-2">Read More <i class="fa fa-caret-right" aria-hidden="true"></i></a>*@
                            <a href="@Url.Action("Index","Gym")"> &nbsp;Details &nbsp;<i class="fa fa-caret-right" aria-hidden="true"></i></a>
                            </div>
                        </div>
                    </div>
                </div>
            </li>
            <li>
                <div class="banner-top1">
                    <div class="layer">
                        <div class="container">
                            <div class="banner-info_agile_w3ls">
                                <h3>Looking For A<span>Hostel.</span></h3>
                                <p>Hostel accomodation available here.</p>
                                @*<a href="About" class="mr-2">Read More <i class="fa fa-caret-right" aria-hidden="true"></i></a>*@
                            <a href="@Url.Action("Index","Hostel")"> &nbsp;Details &nbsp;<i class="fa fa-caret-right" aria-hidden="true"></i></a>
                            </div>
                        </div>
                    </div>
                </div>
            </li>
            <li>
                <div class="banner-top2">
                    <div class="layer">
                        <div class="container">
                            <div class="banner-info_agile_w3ls">
                                <h3>Lets Gain Some <span>Knowledge.</span></h3>
                                <p>Library facility at its best.</p>
                                @*<a href="About" class="mr-2">Read More <i class="fa fa-caret-right" aria-hidden="true"></i></a>*@
                            <a href="@Url.Action("Index","Library")"> &nbsp;Details &nbsp;<i class="fa fa-caret-right" aria-hidden="true"></i></a>
                            </div>
                        </div>
                    </div>
                </div>
            </li>
        </ul>
    </div>  <!-- Social Icons -->
    <!--<div class="w3_agileits_social_media">
        <ul>
            <li><a href="#" class="wthree_facebook"><i class="fa fa-facebook" aria-hidden="true"></i></a></li>
            <li><a href="#" class="wthree_twitter"><i class="fa fa-twitter" aria-hidden="true"></i></a></li>
            <li><a href="#" class="wthree_dribbble"><i class="fa fa-dribbble" aria-hidden="true"></i></a></li>
            <li><a href="#" class="wthree_behance"><i class="fa fa-behance" aria-hidden="true"></i></a></li>
        </ul>
    </div>-->
    <!-- //Social Icons -->
    <div class="clearfix"> </div>




    @*<p class="ab">connect with us</p>*@

    <!-- To bottom button-->
    <div class="thim-click-to-bottom">
        <div class="rotate">
            <a href="#Service" class="scroll">
                <i class="fa fa-ellipsis-v"></i>
            </a>
        </div>
    </div>
    <!-- //To bottom button-->
</div>
<!--//Slider-->
<!-- /services -->
<section class="featured_services py-5" id="Service">
    <div class="container py-3">
        <h3 class="heading text-center mb-5">Our Services</h3>
        <div class="row agile_inner_info">
            <div class="col-lg-4 col-md-6 w3_agile_services_grid">
                <div class="agile_services_grid">
                    <div class="hover06 column">
                        <div>
                            <figure><img src="~/images/young-fitness.jpg" alt=" " class="img-responsive"></figure>
                        </div>
                    </div>
                    <div class="agile_services_grid_pos">
                        <i class="fa fa-heart" aria-hidden="true"></i>
                    </div>
                </div>
                <h4>Gym</h4>
                <p>Lorem ipsum dolor sit amet, do eiusmod tempor incididunt .Aliquam lacus turpis.</p>
            </div>
            <div class="col-lg-4 col-md-6 mt-md-0 mt-5 w3_agile_services_grid">
                <div class="agile_services_grid">
                    <div class="hover06 column">
                        <div>
                            <figure><img src="~/images/room-dormitory1.jpg" alt=" " class="img-responsive"></figure>
                        </div>
                    </div>
                    <div class="agile_services_grid_pos">
                        <i class="fa fa-bed" aria-hidden="true"></i>
                    </div>
                </div>
                <h4>Hostel</h4>
                <p>Lorem ipsum dolor sit amet, do eiusmod tempor incididunt .Aliquam lacus turpis.</p>
            </div>
            <div class="col-lg-4 col-md-6 mt-lg-0 mt-5 w3_agile_services_grid">
                <div class="agile_services_grid">
                    <div class="hover06 column">
                        <div>
                            <figure><img src="~/images/library-desk.jpg" alt=" " class="img-responsive"></figure>
                        </div>
                    </div>
                    <div class="agile_services_grid_pos">
                        <i class="fa fa-book" aria-hidden="true"></i>
                    </div>
                </div>
                <h4>Library</h4>
                <p>Lorem ipsum dolor sit amet, do eiusmod tempor incididunt .Aliquam lacus turpis.</p>
            </div>
            <div class="mx-auto mt-lg-4 mt-5 text-center">
                <a href="services.html">Explore all Services</a>
            </div>
        </div>
    </div>
</section>
<!-- //services -->
<!--/middle-->
<section class="middle-sec-agileinfo-w3ls py-5">
    <div class="container py-3">
        <h3 class="heading text-center mb-5"> Latest Tour Blog </h3>
        <div class="row inner-sec">
            <div class="col-lg-4 col-md-6 news-left">
                <ul id="demo1_thumbs" class="list-inline">
                    <li>
                        <a href="~/images/banner1.jpg">
                            <img src="~/images/b1.jpg" alt="" data-desoslide-caption="<h3>Latest Post 1</h3>">
                            <div class="mid-text-info">
                                <h4>Maecenas aliqua Aenean aliquam porta sem ins.</h4>
                                <p class="font-italic">posted 2 days ago </p>
                            </div>
                        </a>
                    </li>
                    <li>
                        <a href="~/images/banner2.jpg">
                            <img src="~/images/b2.jpg" alt="" data-desoslide-caption="<h3>Latest Post 2</h3>">
                            <div class="mid-text-info">
                                <h4>Maecenas aliqua Aenean aliquam porta sem ins.</h4>
                                <p class="font-italic">posted 2 days ago </p>
                            </div>
                        </a>
                    </li>
                    <li>
                        <a href="~/images/banner5.jpg">
                            <img src="~/images/b5.jpg" alt="" data-desoslide-caption="<h3>Latest Post 3</h3>">
                            <div class="mid-text-info">
                                <h4>Maecenas aliqua Aenean aliquam porta sem ins.</h4>
                                <p class="font-italic">posted 2 days ago </p>
                            </div>
                        </a>
                    </li>
                    <li>
                        <a href="~/images/banner4.jpg">
                            <img src="~/images/b4.jpg" alt="" data-desoslide-caption="<h3>Latest Post 4</h3>">
                            <div class="mid-text-info">
                                <h4>Maecenas aliqua Aenean aliquam porta sem ins.</h4>
                                <p class="font-italic">posted 2 days ago </p>
                            </div>
                        </a>
                    </li>
                </ul>
            </div>
            <div id="demo1_main_image" class="col-lg-8 col-md-6 news-right">
                <h4 class="text-uppercase mb-4">Adventure Travel Point </h4>
            </div>
            <div class="clearfix"> </div>
        </div>
    </div>

</section>
<!--//middle-->
<!-- team -->
<div class="team py-5">
    <div class="agile_dot_info two">
        <div class="container">
            <h3 class="heading text-center mb-5">Our Team</h3>
            <div class="row agileits_team_grids">
                <div class="col-lg-3 col-sm-6 agileits_team_grid">
                    <div class="agileits_team_grid_figure">
                        <img src="~/images/b1.jpg" alt=" " class="img-responsive" />
                    </div>
                    <div class="agileits_team_grid_figure_social">
                        <ul class="w3ls_social">
                            <li><a href="#" class="w3_agile_facebook"><i class="fa fa-facebook" aria-hidden="true"></i></a></li>
                            <li><a href="#" class="w3_agile_dribble"><i class="fa fa-dribbble" aria-hidden="true"></i></a></li>
                        </ul>
                    </div>
                    <div class="clearfix"> </div>
                    <h4> Charlotte <span>guide</span></h4>
                    <p>Morbi non elit sed neque init rhoncus maximus ac enim.</p>
                </div>
                <div class="col-lg-3 col-sm-6 agileits_team_grid">
                    <div class="agileits_team_grid_figure">
                        <img src="~/images/b1.jpg" alt=" " class="img-responsive" />
                    </div>
                    <div class="agileits_team_grid_figure_social">
                        <ul class="w3ls_social">
                            <li><a href="#" class="w3_agile_facebook"><i class="fa fa-facebook" aria-hidden="true"></i></a></li>
                            <li><a href="#" class="w3_agile_dribble"><i class="fa fa-dribbble" aria-hidden="true"></i></a></li>
                        </ul>
                    </div>
                    <div class="clearfix"> </div>
                    <h4>Isabella <span>guide</span></h4>
                    <p>Morbi non elit sed neque init rhoncus maximus ac enim.</p>
                </div>
                <div class="col-lg-3 col-sm-6 agileits_team_grid">
                    <div class="agileits_team_grid_figure">
                        <img src="~/images/b2.jpg" alt=" " class="img-responsive" />
                    </div>
                    <div class="agileits_team_grid_figure_social">
                        <ul class="w3ls_social">
                            <li><a href="#" class="w3_agile_facebook"><i class="fa fa-facebook" aria-hidden="true"></i></a></li>
                            <li><a href="#" class="w3_agile_dribble"><i class="fa fa-dribbble" aria-hidden="true"></i></a></li>
                        </ul>
                    </div>
                    <div class="clearfix"> </div>
                    <h4>Alexander  <span>guide</span></h4>
                    <p>Morbi non elit sed neque init rhoncus maximus ac enim.</p>
                </div>
                <div class="col-lg-3 col-sm-6 agileits_team_grid">
                    <div class="agileits_team_grid_figure">
                        <img src="~/images/b2.jpg" alt=" " class="img-responsive" />
                    </div>
                    <div class="agileits_team_grid_figure_social">
                        <ul class="w3ls_social">
                            <li><a href="#" class="w3_agile_facebook"><i class="fa fa-facebook" aria-hidden="true"></i></a></li>
                            <li><a href="#" class="w3_agile_dribble"><i class="fa fa-dribbble" aria-hidden="true"></i></a></li>
                        </ul>
                    </div>
                    <div class="clearfix"> </div>
                    <h4>Laura Carl <span>guide</span></h4>
                    <p>Morbi non elit sed neque init rhoncus maximus ac enim.</p>
                </div>
            </div>
        </div>
    </div>
</div>
<!-- //team -->

GHL/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    <!-- Meta tag Keywords -->
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta charset="utf-8">
    <meta name="keywords" content="Adventure Travel Point" />
    <script type="application/x-javascript">
        addEventListener("load", function () {
            setTimeout(hideURLbar, 0);
        }, false);

        function hideURLbar() {
            window.scrollTo(0, 1);
        }
    </script>
    <!--// Meta tag Keywords -->
    <!-- pop up box -->
    <link href="~/css/popuo-box.css" rel="stylesheet" type="text/css" media="all" />
    <!-- //pop up box -->

    <link rel="stylesheet" href="~/css/jquery.desoslide.css">

    <!-- css files -->
    <link rel="stylesheet" href="~/css/bootstrap.css"> <!-- Bootstrap-Core-CSS -->
    <link rel="stylesheet" href="~/css/style.css" type="text/css" media="all" /> <!-- Style-CSS -->
    <link rel="stylesheet" href="~/css/font-awesome.css"> <!-- Font-Awesome-Icons-CSS -->
    <link rel="stylesheet" href="~/Content/font-awesome.min.css" />
    <link rel="stylesheet" href="~/Content/animate.min.css" />
    <!-- //css files -->

    <link rel="stylesheet" href="~/css/jquery-ui.css" />
    <!-- web-fonts -->
    <link href="//fonts.googleapis.com/css?family=Raleway:100,100i,200,200i,300,300i,400,400i,500,500i,600,600i,700,700i,800,800i,900,900i&amp;subset=latin-ext" rel="stylesheet">
    <!-- //web-fonts -->
    @*@Styles.Render("~/Content/css")
        @Scripts.Render("~/bundles/modernizr")*@
</head>
<body>

    <!--Header-->
    <header>
        <div class="container agile-banner_nav">
            <div class="row header-top">
                <div class="col-md-5 top-left p-0">
                    <p><i class="fa fa-phone" aria-hidden="true"></i> Call us : +91-9871775527, +91-9953495340 </p>
                </div>
                <div class="col-md-7 top-right p-0">
                    <p><i class="fa fa-map-marker" aria-hidden="true"></i>A1/470 Main Market, Shakarpur, East Delhi-110092
</div>
            </div>

            <nav class="navbar navbar-expand-lg navbar-light bg-light">

                @*<h1><a class="navbar-brand" href="Index">A T P</a></h1>*@
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>

                <div class="collapse navbar-collapse justify-content-center" id="navbarSupportedContent">
                    <ul class="navbar-nav ml-auto">
                        <li class="nav-item">
                            <a class="nav-link" href="@Url.Action("Index","Home")">Home @*<span class="sr-only">(current)</span>*@</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="@Url.Action("About","Home")">About</a>
                        </li>
                        <li class="dropdown nav-item">
                            <a href="#" class="dropdown-toggle nav-link" data-toggle="dropdown">
                                Services
                                <b class="caret"></b>
                            </a>
                            <ul class="dropdown-menu agile_short_dropdown">
                                <li>
                                    <a href="@Url.Action("Index","Gym")">GYM</a>
                                </li>
                                <li>
                                    <a href="@Url.Action("Index","Hostel")">HOSTEL</a>
                                </li>
                                <li>
                                    <a href="@Url.Action("Index","Library")">LIBRARY</a>
                                </li>
                            </ul>
                        </li>
                        <li class="nav-item pr-lg-0">
                            <a class="nav-link pr-lg-0" href="@Url.Action("Contact","Home")">Contact</a>
                        </li>
                        <li class="dropdown nav-item">
                            <a href="#" class="dropdown-toggle nav-link" data-toggle="dropdown">
                                User
                                <b class="caret"></b>
                            </a>
                            <ul class="dropdown-menu agile_short_dropdown">
                                <li>
                                    <a href="@Url.Action("Login","Home")">Login</a>
                                </li>
                                <li>
                                    <a href="@Url.Action("Login","Home")">Register</a>
                                </li>
                            </ul>
                        </li>
                    </ul>
                </div>

            </nav>
        </div>
    </header>
    <!--Header-->



    @RenderBody()

    <!-- footer -->
    <footer class="py-5">
        <div class="container py-md-3">
            <div class="row footer-grids pb-md-5 pb-3">
                <div class="col-lg-12">
                    <div class="row">
                        <div class="col-md-4 col-sm-6 col-6 pl-5">
                            <a href="#"> <i class="fa fa-envelope ml-5"></i>Send Message</a>
                        </div>
                        <div class="col-md-4 col-sm-6 col-6 mt-md-0 mt-2 pl-5">
                            <a href="#"> <i class="fa fa-skype ml-5"></i>Skype Call</a>
                        </div>
                        <div class="col-md-4 col-sm-6 col-6 mt-md-0 mt-2 pl-5">
                            <a href="#"> <i class="fa fa-comment ml-5"></i>Online Chat</a>
                        </div>
                    </div>
                </div>
            </div>

            <div class="subscribe-grid text-center">
                <p class="para three mt-4">Lorem ipsum dolor sit amet, consectetur adipiscing elit. Phasellus at placerat ante. Praesent nulla nunc, pretium dapibus efficitur in, auctor eget elit. Lorem ipsum dolor sit amet </p>
                <h5 class="pb-3">Subscribe for our latest updates</h5>
                <form action="#" method="post">
                    <input class="form-control" type="email" placeholder="Subscribe" name="Subscribe" required="">
                    <button class="btn1">
                        <i class="fa fa-paper-plane"></i>
                    </button>
                </form>
            </div>
        </div>
    </footer>
    <!-- //footer -->
    <!-- copyright -->
    <section class="copyright py-4 text-center">
        <div class="container">
            <p>© 2019 All Rights Reserved | Design by <a href="http://zservicedesk.com/" target="=_blank"> ZServiceDesk </a></p>
        </div>
    </section>
    <!-- //copyright -->
    <!-- js-scripts -->
    @*<div class="container body-content">*@

    @*<hr />*@
    @*<footer>
            <p>&copy; @DateTime.Now.Year - My ASP.NET Application</p>
        </footer>*@
    @*</div>*@

    @*@Scripts.Render("~/bundles/jquery")
        @Scripts.Render("~/bundles/bootstrap")
        @RenderSection("scripts", required: false)*@
    <!-- js-scripts -->
    <!-- js -->
    <script type="text/javascript" src="~/js/jquery-2.2.3.min.js"></script>
    <script type="text/javascript" src="~/js/bootstrap.js"></script> <!-- Necessary-JavaScript-File-For-Bootstrap -->
    <!-- //js -->
    <!-- desoslide-JavaScript -->
    <script src="~/js/jquery.desoslide.js"></script>
    <script>
        $('#demo1_thumbs').desoSlide({
            main: {
                container: '#demo1_main_image',
                cssClass: 'img-responsive'
            },
            effect: 'sideFade',
            caption: true
        });
    </script>

    <!-- Calendar -->
    <script src="~/js/jquery-ui.js"></script>
    <script>
        $(function () {
            $("#datepicker,#datepicker1").datepicker();
        });
    </script>
    <!-- //Calendar -->
    <!-- banner slider -->
    <script src="~/js/responsiveslides.min.js"></script>
    <script>
        $(function () {
            $("#slider4").responsiveSlides({
                auto: true,
                pager: true,
                nav: true,
                speed: 1000,
                namespace: "callbacks",
                before: function () {
                    $('.events').append("<li>before event fired.</li>");
                },
                after: function () {
                    $('.events').append("<li>after event fired.</li>");
                }
            });
        });
    </script>
    <!-- //banner slider -->
    <!--pop-up-box -->
    <script src="~/js/jquery.magnific-popup.js"></script>
    <script>
        $(document).ready(function () {
            $('.popup-with-zoom-anim').magnificPopup({
                type: 'inline',
                fixedContentPos: false,
                fixedBgPos: true,
                overflowY: 'auto',
                closeBtnInside: true,
                preloader: false,
                midClick: true,
                removalDelay: 300,
                mainClass: 'my-mfp-zoom-in'
            });
        });
    </script>
    <!-- //pop-up-box -->
    <!-- start-smoth-scrolling -->
    <script src="~/js/SmoothScroll.min.js"></script>
    <script type="text/javascript" src="~/js/move-top.js"></script>
    <script type="text/javascript" src="~/js/easing.js"></script>
    <script type="text/javascript">
        jQuery(document).ready(function ($) {
            $(".scroll").click(function (event) {
                event.preventDefault();
                $('html,body').animate({ scrollTop: $(this.hash).offset().top }, 1000);
            });
        });
    </script>
    <!-- here stars scrolling icon -->
    <script type="text/javascript">
        $(document).ready(function () {
            /*
                var defaults = {
                containerID: 'toTop', // fading element id
                containerHoverID: 'toTopHover', // fading element hover id
                scrollSpeed: 1200,
                easingType: 'linear'
                };
            */

            $().UItoTop({ easingType: 'easeOutQuart' });

        });
    </script>
    <script>
        $('nav li a').filter(function () {
            return this.href === location.href;
        }).addClass('active');
    </script>
    <!-- //here ends scrolling icon -->
    <!-- start-smoth-scrolling -->
    <!-- //js-scripts -->

</body>
</html>